<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-AH527JB" ignored="0" name="RetryMultipleFailedTestCases" tests="9" failures="2" timestamp="2020-10-12T17:28:11 IST" time="0.104" errors="0">
  <testcase name="test1" time="0.009" classname="myTest.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="myTest.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="myTest.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="myTest.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTest.MyTests.test1(MyTests.java:9)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="myTest.MyTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="myTest.MyTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="myTest.MyTests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="myTest.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTest.MyTests.test2(MyTests.java:16)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="myTest.MyTests"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
